Thistle/galley-sdk

setup.py
This updates setup.py to use galley-sdk as the project name, in hopes of fixing an issue where some users cannot install this project. The version is also updated to 0.1.0, to align with semantic versioning.
- Update the galley statement in the importing project to point to this commit and verify that the package is installed correctly, for example: `git+https://github.com/Thistle/galley-sdk.git@3a39acf3e65c626c4379a8ac27d5cb23f160dab3#egg=galley-sdk`
=> (bugfix) update setup.py with correct project name

galley/queries.py, galley/types.py, tests/test_queries.py
Added galley-sdk methods for retrieving recipe ingredients.
get_recipe_ingredients returns the raw graphql objects for the recipe's ingredients.
get_formatted_recipe_ingredients separates the ingredients into ingredients (ingredients
for the main recipe) and standalone_ingredients (ingredients for any standalone components).
The formatted ingredients list removes all packaging "ingredients" and de-dups ingredients
within each list.
One question I have: There were several places where we made the query using viewer(), but my understanding is that adding the () returns all possible fields. That didn't seem desirable, so I removed the parentheses, but want a sanity check that my understanding is correct. (I can add them back in if that's the correct usage)
- Check that tests pass
- Run the …
=> (ENG-762) APIs to retrieve recipe ingredients from Galley

galley/queries.py, galley/types.py, setup.py, tests/test_queries.py
This PR focuses on refactoring our original function `get_week_menu_data` to take in a list of menu names so that only one request is sent to Galley for batched weekly menu data.
Open python interactive within galley-sdk: `$ python`
`>>> from pprint import pprint` (optional: to apply pretty print format to returned data)
`>>> from galley.queries import *` 
`>>> pprint(get_week_menu_data(["2021-10-04 1_2_3", "2021-10-04 4_5_6", "2021-10-25 1_2_3", "2021-10-25 4_5_6"]))`
> **Expectation:** A dictionary return value similar to:
> ```python3
> [{
>    "name": "2021-10-04 1_2_3",
>    "id": "bWVudTo2MzQ2NTY=",
>    "date": "2021-10-04",
>    "location": {"name": "Vacaville"},
>    "menuItems": [{
>       "recipeId": "cmVjaXBlOjE3NDc5MA==",
>       "categoryValues": [{
>          "name": …
```
=> (ENG-837) Retrieve batched weekly menu data

galley/queries.py, galley/types.py, setup.py, tests/test_queries.py
This PR focuses on updating the `get_week_menu_data` function to retrieve specific fields from `recipeItems`; more specifically, the `subRecipeId` and the `name` objects from `preparations` list.
Open python interactive within galley-sdk: `$ python`
`>>> from pprint import pprint` (optional: to apply pretty print format to returned data)
`>>> from galley.queries import *` 
`>>> pprint(get_week_menu_data(["2021-10-25 4_5_6"]))`
> **Expectation:** A return value **similar** to:
> ```python3
> [{
>    "name": "2021-10-25 4_5_6",
>    "id": "bWVudTo4MjY0NTE=",
>    "date": "2021-10-28",
>    "location": {"name": "Vacaville"},
>    "menuItems": [{
>       "recipeId": "cmVjaXBlOjE3NDc5MA==",
>       "categoryValues": [{
>          "name": "lv4",
>          "category": {"itemType": "menuItem", …
```
=> (ENG-825) Add recipeItems to week menu data retrieval

galley/common.py, galley/formatted_queries.py, galley/pagination.py, galley/queries.py, galley/types.py, mypy.ini, tests/mock_responses/mock_menu_data.py, tests/test_common_utils.py, tests/test_formatted_queries.py, tests/test_queries.py
This PR is focused on formatting menu data returned from `get_week_menu_data` by creating a wrapper function, `get_formatted_menu_data`. Notes to consider when reviewing this PR:
> 1.) What we need to know about each menuItem is:
>    - what product_code does it relate to on the thistle-web side (represented by `itemCode` in the expected return value e.g. LV1 or DM3 or RSK)
>    - what top-level recipe is it related to (represented by `recipeId`, e.g. "cmVjaXBlOjE3ODAxMA==" is the id for "Thistle Pad Thai with Sesame Baked Tofu" recipe)
>    - what standalone item is associated with the top-level recipe (represented by `standaloneRecipeId` e.g. "Thistle Pad Thai with Sesame Baked Tofu" recipe has a standalone item with an id of "cmVjaXBlOjE3NDQxMg==" to represent "Chili Tamarind Sauce")
> …
=> (ENG-822) Format menu data

galley/queries.py, setup.py, tests/test_queries.py
This updates the query to correctly batch the request for multiple recipe ids. We should now be correctly filtering packaging, whereas previously packaging ingredients were being included in the ingredients list. It also updates the test to correct the expected query.
In interactive python, run:
`import pprint; import galley`
`pprint(get_formatted_recipes_data(["cmVjaXBlOjE3OTk1Mw==", "cmVjaXBlOjE3Mjg4Mg==", "FAKE!!!"]))`
You can compare these results to the recipes on galley. Note that all packaging and standalone items should be excluded from the ingredients list.
https://staging-app.galleysolutions.com/recipes/cmVjaXBlOjE3OTk1Mw==
https://staging-app.galleysolutions.com/recipes/cmVjaXBlOjE3Mjg4Mg==
Updated to 0.11.1
=> (ENG-823) Bug Fix - corrects viewer.recipe to viewer.recipes for batch query

galley/formatted_queries.py, galley/queries.py, galley/types.py, setup.py, tests/mock_responses/mock_recipe_tree_components.py, tests/mock_responses/mock_recipes_data.py, tests/test_formatted_queries.py, tests/test_queries.py
adds `totalWeight` as output to formatted recipes from `get_formatted_recipes_data`
automated tests passing...
manual test:
```
>>> import pprint; import galley
>>> from galley.formatted_queries import *
>>> result=get_formatted_recipes_data(['cmVjaXBlOjE4MjEzOA=='])
>>> pp = pprint.PrettyPrinter()
>>> pp.pprint(result)
[{'description': None,
'externalName': None,
'id': 'cmVjaXBlOjE4MjEzOA==',
...
'zincPercentRDI': 0.321},
'proteinType': 'vegan',
'totalWeight': 389.80594262499994}]
```
note that if you comment out skipping standalone and packaging items
```
if recipeItem:
recipe_item = RecipeItem(
preparations=recipeItem.get('preparations', []),
ingredient=ingredient if ingredient else None,
quantity_unit_values=recipe_tree_component.get('quantityUnitValues', [])
)
#if …
```
=> (ENG-818) adding weight to recipe details

galley/formatted_queries.py, galley/queries.py, galley/types.py, setup.py, tests/mock_responses/mock_menu_data.py, tests/test_formatted_queries.py, tests/test_queries.py
This adds another attribute, menu item id, to the data that gets retrieved from Galley and returned by get_formatted_menu_data. We will be using menu item id within thistle-web to send menu item projections to Galley. Tests and mock data are updated to account for the new attribute.
Open python interactive within galley-sdk: $ python
`from pprint import pprint` (optional: to apply pretty print format to returned data)
Request formatted menu data for a couple weeks:
`pprint(get_formatted_menu_data(['2022-01-03', '2021-12-27']))`
Validate that for each menu item included in the returned menus, an id is present (can additionally use the Galley playground to validate that the value of the ids matches expectations).
Please update the project version in …
=> (ENG-870) add menu item id to menu data retrieval and formatting functions

galley/enums.py, galley/formatted_queries.py, setup.py, tests/mock_responses/mock_menu_data.py
This fixes a bug where the data returned for the itemCode attribute on menuItems was fluctuating between the product_code and bag_label_header category values. The new behavior ensures that only product_code category value is returned. Tests and fixtures are updated to account for the changes.
Open python interactive within galley-sdk: 
`$ python`
`from pprint import pprint` (optional: to apply pretty print format to returned data)
Request formatted menu data for a couple weeks:
`pprint(get_formatted_menu_data(['2022-01-03', '2021-12-27']))`
Validate that for each menu item included in the returned menus, the itemCode attribute matches what you see in the product_code column for that menu in the Galley UX.
Please update the project version in …
=> (ENG-870) fix bug with menu item category values

galley/enums.py, galley/formatted_queries.py, setup.py, tests/mock_responses/mock_recipes_data.py, tests/test_formatted_queries.py
The focus of this PR is to add two more recipe-level category tag values, `baseMealSlug` and `proteinAddOn`, to the return value of `get_formatted_recipes_data()` for label printing purposes. This PR also ensures that `baseMealSlug`, `proteinAddOn`, and all other existing recipe-level category tags are identified via their id--`categoryId`. Automated tests have been updated to confirm the expected behavior(s).
Open python interactive within galley-sdk: `$ python`
`>>> from pprint import pprint` (optional: to apply pretty print format to returned data)
`>>> from galley.formatted_queries import *`
`>>> pprint(get_formatted_recipes_data(['cmVjaXBlOjE4Mzk4NA==']))`
> **Expectation:** A return value **similar** to:
> ```python3
> [{'baseMealSlug': 'persephone-salad',
>   'description': None,
> …
```
=> (ENG-891) Add baseMealSlug and proteinAddOn tags to recipe data retrieval

galley/queries.py, setup.py, tests/test_queries.py
We recently changed the way we're managing standalone recipes in Galley and updated the related handling in get_formatted_recipes_data() to access standaloneNutrition according to the new recipe structure (with the value of standaloneNutrition being pulled from subrecipe.reconciledNutritionals instead of recipeItem.reconciledNutritionals). While this work was in-flight, an unrelated PR merged that updated the way we query recipe data to use graphQL pagination via recipe_connection_query. These changes passed each other like ships in the night, such that get_formatted_recipes_data() was trying to access data no longer being pulled in by recipe_connection_query(). This fix updates recipe_connection_query to pull in subrecipe.reconciledNutritionals instead of …
=> (maint) adjust recipe connection query to pull back standalone nutrition from correct source

galley/formatted_queries.py, galley/queries.py, setup.py, tests/mock_responses/mock_menu_data.py, tests/test_formatted_queries.py, tests/test_queries.py
This branch pulls the base meal slug and includes it in the formatted responses for menu.
You can check the meal slugs are returned with the formatted queries like so.
```
import galley
from galley.formatted_queries import get_formatted_menu_data
get_formatted_menu_data(['2022-01-03'])
```
[X] Please update the project version in setup.py
=> Eng 943 add recipe meal slug

galley/enums.py, galley/formatted_queries.py, setup.py, tests/mock_responses/mock_recipes_data.py, tests/test_formatted_queries.py
This adds two new fields to the formatted data returned for each recipe. hasStandalone is a boolean field representing whether the recipe includes a standalone component. This new field will allow us to validate on fields specific to the standalone recipe when expected. baseMeal is a categoryValue (tag) being set on each recipe in Galley that we forgot to include in the formatted data previously. Tests are updated to cover the expected behaviors.
To test this, retrieve recipe details for a couple recipes (one w/standalone and one without) and ensure that the `hasStandalone` and `baseMeal` fields are returned with the expected values for each recipe.
This example uses the Balinese Gado Gado Salad (with standalone) and Burmese Yellow Curry(no standalone):
`from galley.formatted_queries …
=> (maint) add hasStandalone and baseMeal fields to formatted recipe data

galley/formatted_queries.py, setup.py
in cases where product code is not assigned to a menu item an `UnboundLocalError` is being thrown
in shell access a menu with a menu item that does not have a product code assigned to it. currently there is one in staging for 10-04-2021
```
from galley.formatted_queries import get_formatted_menu_data
dates = ['2021-10-04']
get_formatted_menu_data(dates=dates)
```
on main, this will generate an `UnboundLocalError` that will go away with this fix
Please update the project version in setup.py
=> (maint) itemCode referenced before assignment fix

galley/formatted_queries.py, galley/queries.py, galley/types.py, setup.py, tests/mock_responses/mock_recipe_tree_components.py, tests/mock_responses/mock_recipes_data.py, tests/test_formatted_queries.py, tests/test_queries.py
This updates get_formatted_recipes_data() and its underlying functions to return a few additional fields about standalone components: standaloneSuggestedServing, standaloneServingSizeWeight, and standaloneServings. 
This new handling allows us to provide more than one serving of a standalone component within a recipe, and display accurate information to customers on labels and in our website as to how many servings of the standalone component are provided. Previously our implementation assumed that we would only ever provide one serving of standalone components. 
Tests are added/updated to account for the expected behaviors.
To test this, retrieve recipe details for a few different cases: a recipe without any standalone component, a recipe with multiple servings of a standalone component, …
=> (ENG-932) add handling for dynamic standalone serving sizes

galley/enums.py, galley/formatted_queries.py, galley/queries.py, galley/types.py, setup.py, tests/mock_responses/mock_recipes_data.py, tests/test_formatted_queries.py, tests/test_queries.py
Updated galley-sdk to pull a recipe's 'media' attribute (a list of RecipeMedia objects) in recipe_connection_query. Updated get_formatted_recipes_data to search the RecipeMedia objects for an object with the caption 'lifestyle'. It then returns the sourceUrl for this RecipeMedia object as the formatted recipe's lifestylePhotoUrl.
1. Make sure all tests are passing
2. Test raw query locally in python console (make sure both images show up in the media attribute):
note: The recipe ID provided is a [fake recipe](https://staging-app.galleysolutions.com/recipes/cmVjaXBlOjE5OTgzOA==) I've modified to have two images, one that has the caption 'lifestyle'. This will be overwritten if this PR isn't reviewed before the overnight job replaces staging data.
```
from galley.queries import * …
```
=> (ENG-990) Pull photos for recipe and return lifestylePhotoUrl

galley/mutations.py, galley/queries.py, galley/types.py, setup.py, tests/test_mutations.py, tests/test_queries.py
This removes the POC query and mutation we added while we were setting up galley-sdk and learning how to use the sgqlc tooling. The query, get_recipe_data(), and mutation, add_recipe_instruction(), are not being used and we have no plans to use them in the future. Related tests and Typing entries are also removed.
I checked that these deletions do not impact our primary query/mutation functions, via entering the python shell and:
- For the query:
`from pprint import pprint`
`pprint(get_formatted_recipes_data(['cmVjaXBlOjE4NzI3Mw==']))`
- For the mutation (example pointed at [this menu in Galley](https://staging-app.galleysolutions.com/menus/bWVudTo5NjYwOTQ=))
`from galley.mutations import *`
`payload = [{"menu_id": "bWVudTo5NjYwOTQ=", "menu_items": …
=> (ENG-1010) remove proof-of-concept code

galley/formatted_queries.py, galley/queries.py, galley/types.py, setup.py, tests/mock_responses/mock_menu_data.py, tests/test_formatted_queries.py, tests/test_queries.py
adding new fields for formatted menu items:
recipeName
recipeMenuPhotoUrl
recipeMealType
recipeProteinType
baseMeal
in shell, use the following to look for presence of new fields
```
>>> from galley.formatted_queries import get_formatted_menu_data
>>> import pprint
>>> pp = pprint.PrettyPrinter()
>>> pp.pprint(get_formatted_menu_data(['2022-01-31']))
```
Please update the project version in setup.py
=> (ENG-998) adding recipe fields for menu items

galley/queries.py, setup.py, tests/test_queries.py
in 0.24.0, we pulled only `externalName` for menu item recipes, but many recipes have only a `name`, so adding that to the query
Compared to `main`, reviewer can see in shell that this adds `recipeName` value for many menu items with this command
```
>>> from galley.formatted_queries import get_formatted_menu_data
>>> import pprint
>>> pp = pprint.PrettyPrinter()
>>> pp.pprint(get_formatted_menu_data(['2022-01-31']))
Please update the project version in setup.py
=> (ENG-998) add name to menu item recipe

galley/formatted_queries.py, setup.py, tests/mock_responses/mock_recipe_tree_components.py, tests/test_formatted_queries.py
We need to differentiate between net weight (weight excluding standalone and packaging) and gross weight (weight including standalone and packaging). This PR renames weight to netWeight, adds the calculation for gross weight, and updates our mocks and tests accordingly.
1. Look through test updates and mocks and make sure that calculated net/gross weights are as expected
2. Test get_formatted_recipes_data on a recipe on galley staging with packaging and standalone component and confirm that the grossWeight returned matches the total weight on the dashboard. The example I've compared against is: https://staging-app.galleysolutions.com/recipes/cmVjaXBlOjE4MjEzOA==
Not that grossWeight is returned in grams, so you'll have to convert to lbs to compare
=> (ENG-1101) Add gross weight to recipes

galley/enums.py, galley/formatted_queries.py, setup.py, tests/mock_responses/mock_recipe_category_values.py, tests/mock_responses/mock_recipes_data.py, tests/test_formatted_queries.py
This adds a new field, "highlight_tags", to the response provided by get_formatted_recipes_data(). The highlight_tags field is an array of string values representing what has been assigned to the recipe for the highlight_1 and highlight_2 categories. If no highlight tags have been applied to the recipe, the highlight_tags field is expected to be an empty array.
To manually test that the new "highlight_tags" field is behaving as expected, I updated recipe tags as necessary (as there aren't many tags already applied to recipes) and then went into the python shell and pulled recipe data for those recipes: 
`python`
`from pprint import pprint` (optional)
`pprint(get_formatted_recipes_data(['cmVjaXBlOjE2NzEwOQ==']))` -> [Gado Gado Salad with …
=> (ENG-873) retrieve highlight tags from Galley

galley/formatted_queries.py, galley/queries.py, galley/types.py, setup.py, tests/mock_responses/mock_ops_menu_data.py, tests/test_ops_queries.py
This PR adds query fields to our existing `get_ops_menu_query` function that allows us to retrieve allergen data at the `subRecipe` layers. 
```python
(galley-env) python
>>> import galley; from galley.formatted_queries import *; from pprint import pprint; import json
>>> pprint(get_formatted_ops_menu_data(["2022-03-28", "2022-03-31"]))
>>> menu_items = get_formatted_ops_menu_data(["2022-03-28"])[0]["menuItems"]
>>> menu_item = [m for m in menu_items if m["recipeId"] == "cmVjaXBlOjE5MjY2MQ=="][0]
>>> pprint(menu_item)
>>> print(json.dumps(menu_item, indent=4))
```
1. Check that `recipe.recipeTreeComponents[i].recipeItem.subRecipe.dietaryFlagsWithUsages` is present (expected value for a subRecipe without allergens is `[]`). If `recipe.recipeTreeComponents[i].recipeItem.subRecipe == None`, …
=> (ENG-1204) Pull allergen information into menu ops query

galley/formatted_ops_queries.py, galley/formatted_queries.py, galley/queries.py, setup.py, tests/mock_responses/mock_ops_menu_data.py, tests/test_ops_formatted_queries.py, tests/test_ops_queries.py
Add `menuItemId` field to formatted ops query data & pull in menu item volume unit.
```python3
$ python
>>> import galley; from galley.formatted_ops_queries import *; import json
>>> print(json.dumps(get_formatted_ops_menu_data(["2022-03-21", "2022-05-02"]), indent=4))
```
=> Add menuItemId to formatted ops data & update tests

galley/formatted_ops_queries.py, setup.py
This tweaks the logic within format_bin_weight() to be a bit simpler and resolves a Type Error that was being thrown in local environments. The expected behavior and return values of format_bin_weight() are unchanged and look to be adequately covered by tests, so no test changes are included here.
To confirm that this has no impact on the overall binWeight behavior, you could go into the python shell and run the `get_formatted_ops_menu_data()` function (which returns a `binWeight` attribute for recipeComponents):
`python`
`from pprint import pprint` (optional)
`from galley.formatted_ops_queries import *`
`pprint(get_formatted_ops_menu_data(["2022-05-09", "2022-05-12"]))`
- [x ] Please update the project version in setup.py
=> (maint) fix type error in format_bin_weight()

galley/formatted_ops_queries.py, setup.py, tests/mock_responses/mock_ops_menu_data.py, tests/test_ops_formatted_queries.py
This PR targets `get_formatted_ops_menu_data()` to only return menu item data for specific meal codes, specifically our base meals, jar salads, and side soups. The whitelisted meal codes are:
BASE MEALS: **S1-6, B1-6, LV1-6, LM1-6, DV1-6, DM1-6**
JAR SALADS: **SSA, SSB, SSC, SSD**
SIDE SOUPS: **SCW, SCH, SP, SM**
```python3
(galley-env) python
```
```python3
>>> import galley; from galley.formatted_ops_queries import *
>>> MENUS = get_formatted_ops_menu_data(["2022-06-06", "2022-06-09"])        # full week menu (1_2_3 & 4_5_6)
>>> len(MENUS[0]['menuItems']) + len(MENUS[1]['menuItems'])                  # 52 = 2 * (18 BASE MEALS + 4 JAR SALADS + 4 SIDE SOUPS)
>>> MEAL_CODES = {mi['mealCode'] for m in MENUS for mi in m['menuItems']}    # set of all meal codes returned from MENUS
>>> …
```
=> (FRU-67) Edit ops menu query to return menu items for only whitelisted meal codes

galley/formatted_queries.py, galley/queries.py, galley/types.py, setup.py, tests/mock_responses/mock_menu_data.py, tests/mock_responses/mock_ops_menu_data.py, tests/mock_responses/mock_recipes_data.py, tests/test_formatted_queries.py, tests/test_queries.py
adding `version` to response for `get_formatted_recipes_data`
automated tests and to test manually, since version is not available in staging, 
1. log in to galley staging dashboard
2. select a recipe
3. edit something (easy is the name) to generate a version. (feel free to edit several times if you want to test pagination in query when there are many versions)
4. open shell
5. `>>> from galley.formatted_queries import get_formatted_recipes_data`
6.  confirm `version` is in the output of `>>> get_formatted_recipes_data(['<recipeID_for_recipe_with_versions_you_created'])`
Please update the project version in setup.py
=> (VEG-88) adding version to recipe

galley/formatted_queries.py, setup.py, tests/test_formatted_queries.py
Fixes capitalizing the `'s` in the base meal name. Python's `.title()` function will capitalize any letter in a string that is not preceded by an a-z character causing title formatting such as `Forager'S Pie`.
[Here is a Gist](https://gist.github.com/ErikBrown/8299d970e269a05d53336cc1996894f4) that includes:
- [Base meals raw](https://gist.githubusercontent.com/ErikBrown/8299d970e269a05d53336cc1996894f4/raw/2414fd9261e005dfb4205f86ea448b02ffc2f5ec/base_meals_raw)
- [Base meals formatted with .title()](https://gist.githubusercontent.com/ErikBrown/8299d970e269a05d53336cc1996894f4/raw/9750a838791bfc91eb5bebd32e04ede85e69035f/base_meals_using_title)
- [Base meals formatted with .title() and regex()](https://gist.githubusercontent.com/ErikBrown/8299d970e269a05d53336cc1996894f4/raw/2414fd9261e00 …
=> Fixed capitalizing the apostrophe s in base meal

galley/formatted_ops_queries.py, setup.py, tests/mock_responses/mock_ops_menu_data.py
```python
from galley.formatted_ops_queries import *; import json
print(json.dumps(get_formatted_ops_menu_data(["2022-09-12"]), indent=4))
```
=> Add ounce conversion to formatted menu ops

galley/enums.py, galley/queries.py, galley/types.py, tests/test_ops_queries.py, tests/test_queries.py
Adds location_id to the `get_menu_query` and `get_ops_menu_query` functions. There is a limit of 25 menus returned, and had been fetching ALL menus then filtering them down. This will cause issues once we activate the Burlington menus. This PR adds a filter to the GraphQL query itself so we don't need to return as much data.
Test that `get_raw_menu_data` returns only the menus for the location provided to it. Here's some code to help with that testing:
```
from galley.queries import get_raw_menu_data
expected_dates = ['2022-10-10', '2022-10-13', '2022-10-17', '2022-10-20', '2022-10-24', '2022-10-27', '2022-10-31', '2022-11-03', '2022-11-07', '2022-11-10']
raw_data_burlington = get_raw_menu_data(expected_dates, 'Burlington', 'production')
len(raw_data_burlington) # Should be 10 …
```
=> Added location to menu query

galley/types.py, setup.py, tests/mock_responses/mock_nutrition_data.py, tests/mock_responses/mock_recipe_tree_components.py, tests/test_formatted_queries.py, tests/test_queries.py
Adds the nutrition values `addedSugarPercentDRV` and `saturatedFatPercentDRV` to our queries.
In a python console:
```
from galley.formatted_queries import get_formatted_recipes_data
get_formatted_recipes_data(recipe_ids=["cmVjaXBlOjE3ODAwMg=="])
```
=> Add PercentDRV for addedSugar and saturatedFat

galley/formatted_ops_queries.py, setup.py, tests/mock_responses/mock_ops_menu_data.py
This updates ops queries to use ingredient names instead of externalNames in primary components.
in a python console:
```
from galley.formatted_ops_queries import *
get_formatted_ops_menu_data(dates=['2022-10-31'])
```
Check that you see `'spring mix & arugula PF, SEND TO PLATE'` instead of `'Spring Mix Lettuce*, Baby Arugula*'` in the output
=> (FRU-278) Use ingredient name instead of externalName

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, README.md
Adds an optional dev container for those that don't want to install and manage python environments locally. Automatically includes vscode integration for running and debugging tests as well as everything else needed to develop build and test the library.
1. Open up the library in vscode
2. Click "Reopen In Container" in popup
3. Open the test explorer (beaker/flask in left tab bar)
4. Let the test explore discover the tests
5. Run all test in test explorer(▶️ )
6.  [ ] verify that all tests are green
There is no need to update the version as this has no effect on the library itself.
=> Add dev container

galley/formatted_queries.py, galley/queries.py, galley/types.py, tests/test_formatted_queries.py, tests/test_queries.py
Please include a summary of the change. List any dependencies that are required for this pull request.
1. In Galley staging, pull up a recipe like [Cuban Ropa Vieja with Plantains and Jackfruit Ropa Vieja](https://staging-app.galleysolutions.com/recipes/cmVjaXBlOjE4NTUxMA==?userLocationId=bG9jYXRpb246MTkyOA%3D%3D) that has base recipe, and sub recipes with multiple vendor items.
2. Navigate to a location specific vendor item (West or East Coast) for a sub recipe, and add ingredients to the ingredients list field. Repeat for another sub recipe. 
3. In the galley-sdk virtual environment, call `get_formatted_recipes_data` and `get_raw_recipes_data` with the recipe id and location name of the vendor item you modified. Example queries for Cuban Ropa Vieja, Burlington:
```
import galley
from …
```
=> VEG-249: update ingredient handling

galley/queries.py, setup.py
This reduces the default page size used for queries to Galley's API to 20 instead of 25, upon request from Galley's engineering team. They are experiencing performance issues related to our queries and think a smaller max page size will help.
You can test that the default page size var can safely be changed in this way by setting it to a low number (like 2) and pulling a batch of recipe details, then setting to to _another_ low number (like 3) and pulling the same batch. The output you receive should be the same no matter what the page size var is. To retrieve recipe details:
- Enter the shell via `python`
- `import galley`
- `from galley.queries import *`
- `recipe_ids = ["cmVjaXBlOjE2NDgzNQ==", "cmVjaXBlOjE2NTE3NA==", "cmVjaXBlOjE2NTE3NQ==", "cmVjaXBlOjE2NTE3Ng==", …
=> (HRB-346) Reduce default page size to 20

galley/formatted_ops_queries.py, galley/queries.py, galley/types.py, setup.py, tests/mock_responses/mock_ops_menu_data.py, tests/test_ops_formatted_queries.py, tests/test_ops_queries.py
- Refactors `get_ops_menu_query` and `get_formatted_ops_menu_data` that powers all menu/recipe data Okra receives to reduce inefficiencies caused by querying nested `recipeTreeComponents` and `quantityUnitValues`
- Query pulls in the entire flattened list of `recipeTreeComponents` and uses `ancestorComponentIds` to filter and build a DAG recipe mapping for plating and staging data
- Query replaces `quantityUnitValues` with `unit.UnitValues` for unit conversions
1. Run a previous version of galley-sdk **before** v0.45.0
2. Open python shell and run:
```python
from galley.formatted_ops_queries import *; from pprint import pprint
pprint(get_formatted_ops_menu_data(['2023-04-10', '2023-04-13', '2023-04-17', '2023-04-20', '2023-04-24', '2023-04-27'], 'Vacaville'))
```
3. Copy and paste output …
=> (ENG-1675) Refactor menu ops query

galley/queries.py, galley/types.py
Revision PR to add 'files' to `get_menu_query`
In the python shell run the following: 
```python
from galley.formatted_queries import *
from galley.formatted_ops_queries import *
VACA, BURL = 'Vacaville', 'Burlington'
DATES = ['2024-03-04', '2024-03-11', '2024-03-18']
get_formatted_menu_data(dates=DATES, location_name=VACA)
get_formatted_menu_data(dates=DATES, location_name=BURL)
get_formatted_recipes_data(["cmVjaXBlOjE5MDkwMg=="], VACA)
get_formatted_recipes_data(["cmVjaXBlOjE5MDkwMg=="], BURL)
get_formatted_ops_menu_data(dates=DATES, location_name=VACA)
get_formatted_ops_menu_data(dates=DATES, location_name=BURL)
```
No change
=> (ENG-2578) Add files to get_menu_query

galley/enums.py, galley/formatted_queries.py, setup.py
This is to add "sesame" to our allergen labels in thistle-web by mapping to the "sesame seeds" dietaryFlag in Galley.
```python
from galley.formatted_queries import *
VACA, BURL = 'Vacaville', 'Burlington'
DATES = ['2024-03-04', '2024-03-11', '2024-03-18']
get_formatted_menu_data(dates=DATES, location_name=VACA)
get_formatted_menu_data(dates=DATES, location_name=BURL)
```
```python
from galley.formatted_queries import *
VACA, BURL = 'Vacaville', 'Burlington'
DATES = ['2024-03-04', '2024-03-11', '2024-03-18']
RECIPES = ['cmVjaXBlOjE4MTY2OQ==', 'cmVjaXBlOjE4MTY3MA==']
get_formatted_recipes_data(RECIPES, location_name=VACA)
get_formatted_recipes_data(RECIPES, location_name=BURL)
```
v1.1.0 -> v1.2.0
=> Add sesame seeds dietaryFlag to formatted queries allergen labels

galley/formatted_ops_queries.py, setup.py, tests/test_ops_formatted_queries.py
- The `MEAL_CODES_WHITELIST` has been extracted out of galley-sdk
- `get_formatted_ops_menu_data` accepts a set or list of meal codes to filter from
1. Run `python`
2. Run
```python
from galley.formatted_ops_queries import *
dates = ['2024-08-05', '2024-08-08']
product_codes_filter = {'lv1', 'dm2', 'lm4', 'dv6', 'cwsv', 'cwsm', 'cptv', 'cptm'}
get_formatted_ops_menu_data(dates, meals)
```
1.2.0 -> 1.3.0
=> (ENG-2934) Ops query function accepts an approved list of product codes to filter

galley/formatted_queries.py, galley/queries.py, setup.py, tests/mock_responses/mock_menu_data.py, tests/test_formatted_queries.py
Formatted menu query now returns `volume` for each menu item in a menu cycle.
```python
python
```
```python
from galley.formatted_queries import *
from pprint import pprint
pprint(get_formatted_menu_data(dates=["2024-09-09", "2024-09-12"]))
```
1.3.0 → 1.4.0
=> (ENG-3034) Update formatted menu query to retrieve volume count

galley/formatted_ops_queries.py, galley/queries.py, galley/types.py, setup.py, tests/mock_responses/mock_ops_menu_data.py
This sets up the data that OKRA needs to be able to identify allergen ingredients within the subcomponents of the primary components.
In the python interactive shell, run:
```python
from galley.formatted_ops_queries import *
import json 
BASE_CODES = ['s', 'b', 'lv', 'lm', 'dv', 'dm', 't'] 
BASE_MEALS = {f'{b}{n+1}' for b in BASE_CODES for n in range(6)}
JAR_SALADS = {'ssa', 'ssb', 'ssc', 'ssd'}
SIDE_SOUPS = {'scw', 'sp',  'sm',  'sch'}
THISTLE_CLASSICS = {'cwsv', 'cwsm', 'cptv', 'cptm'}
PRODUCT_CODES_ALLOWED = BASE_MEALS | JAR_SALADS | SIDE_SOUPS | THISTLE_CLASSICS
print(json.dumps(get_formatted_ops_menu_data(dates=["2025-04-10"], product_codes_filter=PRODUCT_CODES_ALLOWED), indent=4))
```
1.4.0 → 1.5.0
=> Update ops query to include a flattened list of all subrecipe ingredients

galley/formatted_ops_queries.py, galley/queries.py, galley/types.py, setup.py
Our menu ops query was consistently timing out after we added the `recipeItemPreparations` field to the `Preparation` type. If this field isn't filtered out of the query, it causes an excessive amount of data to be returned, leading to timeouts. Updating the query to only return the `id` and `name` fields for preparations allows the request to complete successfully for all expected menu dates per facility.
In python interactive shell, run:
```python
from galley.formatted_ops_queries import *; 
BASE_CODES = ['s', 'b', 'lv', 'lm', 'dv', 'dm', 't']
BASE_MEALS = {f'{b}{n+1}' for b in BASE_CODES for n in range(6)}
JAR_SALADS = {'ssa', 'ssb', 'ssc', 'ssd'}
SIDE_SOUPS = {'scw', 'sp',  'sm',  'sch'}
THISTLE_CLASSICS = {'cwsv', 'cwsm', 'cptv', 'cptm'}
PRODUCT_CODES_ALLOWED = BASE_MEALS | …
```
=> Filter preparation field to fix request timeout
